#### Problem Statement
Arjun, Darsh and Harsha are planning to go for a few day's trips. They need to know the budget for different numbers of days. For example, they want to go to OOTY for 3 days. Develop an ML algorithm to help find the best budget trip based on the distance (kilometer) and the number of days using the DataScience.

#### Dataset
The dataset used here is own dataset

In [2]:
# Importing Libraries 
# Assigning the datset to a variable using pandas
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/budget.csv")
df

distance  days  budget
0        90     2    3000
1       120     3    3800
2       122     5    4000
3       130     6    5000
4       133     8    6000
5       140     8    8000
6       142     6    6000

In [3]:
#Checking if there are any null values
df.isnull()

distance   days  budget
0     False  False   False
1     False  False   False
2     False  False   False
3     False  False   False
4     False  False   False
5     False  False   False
6     False  False   False

In [4]:
df.isnull().count()

distance    7
days        7
budget      7
dtype: int64

In [5]:
#Dropping budget column as we need distance and days to predict the budget(y - dependent variable)
x = df.drop('budget',axis = 1)
x

distance  days
0        90     2
1       120     3
2       122     5
3       130     6
4       133     8
5       140     8
6       142     6

In [6]:
#Assigning budget column to y variable
y = df['budget']
y

0    3000
1    3800
2    4000
3    5000
4    6000
5    8000
6    6000
Name: budget, dtype: int64

In [7]:
#importing regression libraries to predict the budget
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression()

In [8]:
reg.predict(x)

array([2529.70030004, 3746.82938341, 4817.65836227, 5517.62465024,
       6611.96102889, 6776.51282743, 5799.71344773])

In [9]:
#score
reg.score(x,y)

0.8229225226886638

In [10]:
#intercept
reg.intercept_

-609.7798604321879

In [11]:
#coefficient
reg.coef_

array([ 23.50739979, 511.90708964])

In [ ]:
km = int(input("Enter the distance: "))
days = int(input("Enter the number of days you're going to stay: "))
price = reg.predict([[km,days]])
print("You will need",price, "for the trip")

You will need [6348.12392543] for the trip


In [ ]:
#Downloading the model
import pickle
with open("budgetmodel","wb") as f:
    pickle.dump(reg,f)

In [13]:
import pickle
import pandas as pd
with open('/content/budgetmodel','rb') as f:
  reg = pickle.load(f)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3452ee6e-511b-4e1a-ad9b-4888eba84525' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>

In [21]:
import numpy as np
clientfile = pd.read_csv("/content/clientfile.csv")
clientfile['days'] = clientfile['days'].fillna(5)
clientfile

distance  days
0       100   5.0
1       200   6.0
2       220   6.0
3       240   5.0
4       260   5.0
5       300   4.0
6       302   2.0
7       308   2.0
8       322   2.0

In [22]:
reg.predict(clientfile)

array([4300.49556687, 7163.14263561, 7633.29063143, 7591.53153761,
       8061.67953343, 8490.06843542, 7513.26905573, 7654.31345447,
       7983.41705155])